# Configuration file for GeoPressureR parameters
#
# This file stores all the parameters used by the GeoPressureR functions, following the best
# practice to separate parameters from codes. This file is used with the config R package
# <https://rstudio.github.io/config/> which allows to retrieve the value of each parameter
# in your analysis files.
#
# This file is meant to be adapted based on your needs: feel free to add or remove parameters either
# in the default or for each tag. It is recommended to specify all parameters used, even if you
# use the default value.

default:
  #-- SET MAP
  tag_set_map:
    extent: [7, 52, -30, 57] # c(W, E, S, N)
    scale: 2 # 1 (min) -> 1째 ; 2 -> 0.5째 ; 5 -> 0.25째 ; 10 (max) -> 0.1째
    include_min_duration: 0 # in hours

  #-- GEOPRESSURE.
  geopressure_map:
    max_sample: 500  #max sample for long stationary periods, not very important, just reduces some computation time
    margin: 10 # in hPa margin in altitude for daily movements of the bird
    sd: 0.8 #key parameter, sd of ERA5 values in the normal distribution
    thr_mask: 0.9 #% of points that have to fall inside the range altitude to be considered
    log_linear_pooling_weight: !expr \(n) log(n)/n

  #-- GRAPH
  graph_create:
    thr_likelihood: 0.9 #the higher the more sqares taken into account; For instance, a value of 0.9 means
    #that we only keep the pixels for which their likelihood sums represent 90% of the total probability space.
    thr_gs: 150 # km/h

  bird_create:
    scientific_name: "Lanius collurio"

  #-- MOVEMENT MODEL
  graph_set_movement: # ?graph_set_movement()
    shape: 6
    scale: 7
    method: "gamma"  #"power" to use the Pmech approach
    low_speed_fix: 20 # km/h
    zero_speed_ratio: 1.3

  graph_add_wind:
    thr_as: 90

  graph_simulation: # ?graph_simulation()
    nj: 10
  pressurepath_create: # ?pressurepath_create()
    variable: ["altitude", "surface_pressure"]
    # solar_dep: 0
  geopressuretemplate: # ?geopressuretemplate()
    likelihood: ["map_pressure"] #  , "map_light"
    outputs: ["marginal", "most_likely", "simulation"]
    pressurepath:  # ["most_likely"]"geopressureviz"


F17:
  id: "F17"
  tag_create:
    crop_start: "2018-07-15"
    crop_end: "2019-06-30"
  tag_set_map:
    known:
      stap_id: [1,-1]
      known_lon: 12.3
      known_lat: 55.9
  geopressure_map:
      log_linear_pooling_weight: !expr \(n) 1.5*log(n)/n
  
X0AD:
  id: "X0AD"
  tag_create:
    crop_start: "2018-07-15"
    crop_end: "2018-12-31" #non exisitng pressure after this time.
  tag_set_map:
    known:
      stap_id: [1]
      known_lon: 12.3
      known_lat: 55.9

X0AA:
  id: "X0AA"
  tag_create:
    crop_start: "2018-07-15"
    crop_end: "2019-06-30"
  tag_set_map:
    known:
      stap_id: [1,-1]
      known_lon: 12.3
      known_lat: 55.9
  geopressure_map:
      log_linear_pooling_weight: !expr \(n) 1.5*log(n)/n
  graph_set_movement: # ?graph_set_movement()
    shape: 6
    scale: 6
  
X0AA2:
  id: "X0AA2"
  tag_create:
    crop_start: "2019-07-01"
    crop_end: "2020-04-03"
  tag_set_map:
    known:
      stap_id: [1]
      known_lon: 12.3
      known_lat: 55.9



A23:
  id: "A23"
  tag_create:
    crop_start: "2017-07-15"
    crop_end: "2018-06-21"
  tag_set_map:
    known:
      stap_id: [1,-1]
      known_lon: 12.3
      known_lat: 55.9
      
    
A16:
  id: "A16"
  tag_create:
    crop_start: "2017-07-15"
    crop_end: "2018-03-21" #Here only including until last wintering period, otherwise tag stops working on 2018-04-12
  tag_set_map:
    known:
      stap_id: [1]
      known_lon: 12.3
      known_lat: 55.9
  #-- GEOLIGHT
  # twl_offset:
  
  
679:
  id: "679"
  tag_create:
    crop_start: "2016-07-15"
    crop_end: "2017-04-01"
  tag_set_map:
    known:
      stap_id: [1]
      known_lon: 12.3
      known_lat: 55.9
  geopressure_map:
      log_linear_pooling_weight: !expr \(n) 1.5*log(n)/n
  graph_set_movement: # ?graph_set_movement()
    shape: 6
    scale: 7
    

X0B4:
  id: "X0B4"
  geopressure_map:
    sd: 0.9
    log_linear_pooling_weight: !expr \(n) 1.5*log(n)/n
  tag_create:
    crop_start: "2018-07-01"
    crop_end: "2019-07-03"
  tag_set_map:
    known:
      stap_id: [1,-1]
      known_lon: 12.3
      known_lat: 55.9
    #-- MOVEMENT MODEL
  graph_set_movement: # ?graph_set_movement()
    shape: 6
    scale: 7
    method: "gamma"  #"power" to use the Pmech approach
    low_speed_fix: 23 # km/h
    zero_speed_ratio: 1.3

  
F11:
  id: "F11"
  tag_create:
    crop_start: "2018-07-15"
    crop_end: "2019-06-18"
  tag_set_map:
    known:
      stap_id: [1,-1]
      known_lon: 12.3
      known_lat: 55.9
    include_min_duration: 0 # in hours
  geopressure_map:
      sd: 0.9
  graph_set_movement: # ?graph_set_movement()
    shape: 6
    scale: 7
    low_speed_fix: 20 # km/h
    zero_speed_ratio: 2
    
    
F24:
  id: "F24"
  tag_create:
    crop_start: "2018-07-015"
    crop_end: "2019-07-04"
  tag_set_map:
    known:
      stap_id: [1,-1]
      known_lon: 12.3
      known_lat: 55.9
  geopressure_map:
    log_linear_pooling_weight: !expr \(n) 1.5*log(n)/n

